name: Storybook Deploy Nuxt

on:
  push:
    branches: [master]

  workflow_dispatch:

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22.14
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          persist-credentials: false
      - name: Install and Build
        run: |
          cd nuxt
          npm install
          npm run build-storybook-full
      - name: Add .nojekyll
        run: |
          cd nuxt/storybook-static
          touch .nojekyll
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@fa24774553152dd7873cd16ebd8d959b010c5445 # v4.9.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages-nuxt
          folder: nuxt/storybook-static
          clean: true
